workflows:
  - name: "register-user"
    flow: "register-user"
    method_ident: "four-fields"
    reset_email: true
    reset_online_id: true
    expected_tokens: [ "access-token" ]

scenarios:
  - name: "registration-missing-first-name"
    description: "Four-fields registration with missing first name"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000a" ]
    sequence: [ "register-user" ]

  - name: "registration-missing-last-name"
    description: "Four-fields registration with missing last name"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000b" ]
    sequence: [ "register-user" ]

  - name: "registration-missing-date-of-birth"
    description: "Four-fields registration with missing date of birth"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000c" ]
    sequence: [ "register-user" ]

  - name: "registration-wrong-country"
    description: "Four-fields registration with wrong country"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000d" ]
    sequence: [ "register-user" ]

  - name: "registration-under-age"
    description: "Four-fields registration with under age"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000e" ]
    sequence: [ "register-user" ]

  - name: "registration-invalid-email"
    description: "Four-fields registration with invalid email"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee000f" ]
    sequence: [ "register-user" ]

  - name: "registration-reused-email"
    description: "Four-fields registration with reused email"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee0010" ]
    sequence: [ "register-user" ]

  - name: "registration-empty-phone"
    description: "Four-fields registration with empty phone"
    supported_namespaces: [ "dev-main", "dev-pkv" ]
    labels: [ "registration", "negative", "00000000-0000-0000-0000-d0c0ffee0011" ]
    sequence: [ "register-user" ]
